-- Recordar incrementar primero el sequence con el "SELECT seq_*SEQUENCE*.nextval from DUAL;" y despues hacer el insert con currval

--Creacion de Sequence
CREATE SEQUENCE SEQ_ABONO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACTIVIDAD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOCIO START WITH 1 INCREMENT BY 1;
-- Creacion Tablas
CREATE TABLE ABONO(ID_ABONO INT PRIMARY KEY, NOMBRE VARCHAR(40), PRECIO DECIMAL, VIGENCIA DATE,TIPO VARCHAR(20));
CREATE TABLE SOCIO(ID_SOCIO INT PRIMARY KEY,NOMBRE VARCHAR(50),APELLIDO VARCHAR(50),DOMICILIO VARCHAR(100),TELEFONO VARCHAR(40),EMAIL VARCHAR(60),ABONO CHAR(15));

CREATE TABLE ACTIVIDAD(ID_ACTIVIDAD INT PRIMARY KEY, TITULO VARCHAR(50), DESCRIPCION VARCHAR(100));
ALTER TABLE ACTIVIDAD ADD COLUMN HORARIO TIME;
ALTER TABLE ACTIVIDAD ADD COLUMN DIA CHAR(10);

CREATE TABLE CERTIFICADO(ID_CERT INT PRIMARY KEY,CERT_FECHA DATE,CERT_MEDICO VARCHAR(60),CERT_OBS VARCHAR(100),ID_SOCIO_FK INT);
ALTER TABLE CERTIFICADO ADD FOREIGN KEY (ID_SOCIO_FK) REFERENCES SOCIO(ID_SOCIO);

-- TABLAS RELACIONALES
CREATE TABLE SOCIO_ACT(
	ID_SOCIO_FK INT NOT NULL,
	ID_ACTIVIDAD_FK INT NOT NULL);
	ALTER TABLE SOCIO_ACT ADD FOREIGN KEY (ID_SOCIO_FK) REFERENCES SOCIO(ID_SOCIO);
	ALTER TABLE SOCIO_ACT ADD FOREIGN KEY (ID_ACTIVIDAD_FK) REFERENCES ACTIVIDAD(ID_ACTIVIDAD);

----INSERTS ACTIVIDADES	-------------------	
	
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'BOXEO','CLASE BOXEO ALTA INTENSIDAD','20:00:00','LUNES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'BOXEO','CLASE BOXEO ALTA INTENSIDAD','20:00:00','MARTES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'BOXEO','CLASE BOXEO ALTA INTENSIDAD','20:00:00','MIERCOLES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'YOGA', 'CLASE YOGA PRINCIPIANTES','13:00:00','MARTES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'YOGA', 'CLASE YOGA PRINCIPIANTES','13:00:00','VIERNES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'YOGA', 'CLASE YOGA PRINCIPIANTES','13:00:00','JUEVES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'YOGA2','CLASE YOGA INTERMEDIOS','11:00:00','MARTES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'YOGA2','CLASE YOGA INTERMEDIOS','11:00:00','LUNES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'YOGA2','CLASE YOGA INTERMEDIOS','11:00:00','MIERCOLES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'YOGA3','CLASE YOGA ALTA INTENSIDAD','18:00:00','MARTES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'YOGA3','CLASE YOGA ALTA INTENSIDAD','18:00:00','MARTES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'ABDOMINALES','CLASE ABOMINALES','10:00:00','LUNES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'ABDOMINALES','CLASE ABOMINALES','10:00:00','MARTES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'ABDOMINALES','CLASE ABOMINALES','10:00:00','MIERCOLES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'ABDOMINALES','CLASE ABOMINALES','10:00:00','JUEVES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'ABDOMINALES','CLASE ABOMINALES','10:00:00','VIERNES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'ABDOMINALES','CLASE ABOMINALES','10:00:00','SABADOS');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'SPINNING','CLASE SPINNING ALTA INTENSIDAD','12:00:00','LUNES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'SPINNING','CLASE SPINNING ALTA INTENSIDAD','12:00:00','MARTES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'SPINNING','CLASE SPINNING ALTA INTENSIDAD','10:00:00','MIERCOLES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'SPINNING','CLASE SPINNING ALTA INTENSIDAD','10:00:00','JUEVES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'SPINNING','CLASE SPINNING ALTA INTENSIDAD','10:00:00','VIERNES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'SPINNING','CLASE SPINNING ALTA INTENSIDAD','10:00:00','SABADOS');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'NATACION','CLASE NATACION','16:00:00','LUNES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'NATACION','CLASE NATACION','16:00:00','MARTES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'NATACION','CLASE NATACION','16:00:00','MIERCOLES');
Insert into ACTIVIDAD values(SEQ_ACTIVIDAD.NEXTVAL,'NATACION','CLASE NATACION','16:00:00','SABADOS');
